### PR TITLE
Prototype/kurobako performance check

### PR DESCRIPTION
**Pull request by jeromepatel**
## Motivation

Prototype test for Kurobako

## Description of the changes

This is a modification of `kurobako-execution-ci` branch. The current implementation still lacks many features such as integrating `github-action-kurobako` and taking into account master branch performance report.

### CODE REVIEW

**Comment by jeromepatel** [comment]
Note: I have updated the kurobako version to 0.2.9. The performance check was not already not working on 0.2.6.
Other changes include defining python version >= 3.7 (a requirement for the test) and removing python/dataset cache command.
The `run_python.py` file works as expected in my local machine, but the same code produces error `ModuleNotFoundError: No module named 'kurobako'` in command `Command 'cat out/studies/CI/studies_CI.json | /__w/optuna/optuna/kurobako run --parallelism 1 > out/results/CI/results_CI.json'`.

**Comment by jeromepatel** [comment]
I am closing this pull request as of now, you can track the progress of this PR at optuna PR #2542

**Comment by nzw0301** [comment]
The linked issue is supposed to be wrong?

**Comment by jeromepatel** [comment]
Sorry, I didn't get your question? Do you mean the Pull request from Optuna #2543 ?

**Pull request closed without merging**
